### ISSUE TITLE
Author affiliations problem

### ISSUE THREAD

**Issue by akokcam** [Valdecy/pyBibX#1]
Thank you for sharing your work. I think that I have found an issue about affiliations. I have a bib database obtained from Web of Science. It seems that if there is a single author in a publication it cannot obtain its affiliation. It returns ['UNKNOW', 'UNKNOW'].

**Comment by Valdecy** [comment]
Can you send me your .bib? I will have a look

**Comment by akokcam** [comment]
Sure, you may find the .bib file in the attachment.

[wos2.zip](https://github.com/Valdecy/pyBibX/files/11748042/wos2.zip)

**Comment by Valdecy** [comment]
Kindly consider updating to version 3.0.2 and verifying if the problem still exists. If the problem persists, please provide a code that replicates the undesired behavior.

**Comment by akokcam** [comment]
I have updated the version 3.0.2 but it worsen the situation. Now it says that, there is only 3 institutions.

> Name: pyBibX
> Version: 3.0.2
> Summary: A Bibliometric and Scientometric Library Powered with Artificial Intelligence Tools
> Home-page: https://github.com/Valdecy/pyBibX
> Author: Valdecy Pereira

<html><body>



Executing the following code shows the "Total Number of Institutions" as 3
`bibfile.eda_bib()`

Main Information | Results
-- | --
Timespan | 1996-2023
Total Number of Countries | 36
Total Number of Institutions | 3


</body>
</html>

**Comment by Valdecy** [comment]
Alright, I believe I have comprehended it now. Please try version 3.0.4, which should display 197 institutions.

**Comment by akokcam** [comment]
It shows 197 institutions but now it still shows the most of the institutions as "UNKNOW."

`bibfile.plot_bars(statistic = 'ipd', topn = 20, size_x = 10, size_y = 5) `

![fig](https://github.com/Valdecy/pyBibX/assets/4437313/c97c5c59-64df-44a7-8dca-f36eb2d60077)

**Comment by Valdecy** [comment]
I recommend giving version 3.0.5 a try as it now correctly identifies all institutions.

**Comment by Valdecy** [comment]
Thank you for using pyBibX! I'm glad I could help. I will work on these issues soon. About the networks, change the argument node_labels = True to node_labels = False
