### ISSUE TITLE
Issue with extracting universities using pybtext - "Unknown" result

### ISSUE THREAD

**Issue by thebrunm97** [Valdecy/pyBibX#10]
Hello everyone,

I've decided to use the pybtext tool to complement the writing of my monograph and I'm on a tight deadline. However, I'm facing some issues when trying to extract the main universities involved in research. For over 111 institutions, the result I'm getting is "unknown".

I've attached an image and a file that illustrate the problem. Has anyone else experienced this or has any idea how I can resolve it quickly?

![imagem_2024-06-28_111850990](https://github.com/Valdecy/pyBibX/assets/170973378/6f457c76-d683-41a2-9430-f210100624e5)

https://drive.google.com/file/d/1MCvQeorFMROG5g4oLnj3tA-DAEQnrJxI/view?usp=sharing

Any help is appreciated!

Bruno Soares

**Comment by Valdecy** [comment]
Please update to pyBibX version 3.3.4. In this version, I have reduced the number of UNKNOWN cases from 111 to 58. However, parsing institution names remains challenging due to the need for a broad standard used by authors and journals.
