### ISSUE TITLE
filter_bib does not allow multiple doctypes

### ISSUE THREAD

**Issue by DietmarKracht** [Valdecy/pyBibX#11]
if (len(doc_type) > 0):
            for item in doc_type:
                if (sum(self.data['document_type'].isin([item])) > 0):
                    docs.append(item) 
                    self.data = self.data[self.data['document_type'].isin(docs)]
                    self.data = self.data.reset_index(drop = True)
                    self.__make_bib(verbose = False)

The last 3 lines of code should not be indented. Otherwise the bibfile does not contain another doctype after the first iteration.

**Comment by Valdecy** [comment]
Thank you for bringing this issue to my attention. You were correct; the last three lines in the filter_bib function should not have been indented inside the loop. I've fixed the code as needed, and the updated version, pyBibX 3.3.5, has been uploaded. I appreciate your valuable feedback and help in improving the library
