### ISSUE TITLE
Error when loading Scopus BibTeX file

### ISSUE THREAD

**Issue by ecksteing** [Valdecy/pyBibX#3]
I am able to successfully import the exported Scopus .bib file e.g. _!wget https://folder.s3.us-east-1.amazonaws.com/scopus-export.bib_ however when I try to load the Scopus .bib file I get the error _AttributeError: 'NoneType' object has no attribute 'group'_ . I successfully import and load WoS files and am just getting this error with Scopus files. 

Here is the issue with error:

```
# Load .bib
# Arguments: file_bib = 'filename.bib'; db = 'scopus', 'wos', 'pubmed'; del_duplicated = True, False
file_name = 'scopus-export.bib'
database  = 'scopus'
bibfile   = pbx_probe(file_bib = file_name, db = database, del_duplicated = True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __get_citations(self, series)
   1226                 try:
-> 1227                     citation[i] = int(citation[i])
   1228                 except:

ValueError: invalid literal for int() with base 10: 'unknow'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
3 frames
[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __get_citations(self, series)
   1227                     citation[i] = int(citation[i])
   1228                 except:
-> 1229                     citation[i] = int(re.search(r'\d+', citation[i]).group())
   1230         return citation
   1231 

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Valdecy** [comment]
Hello There! Can you please send me the .bib file?

**Comment by ecksteing** [comment]
The file is https://usq-working-folder.s3.us-east-1.amazonaws.com/temp/scopus_447.bib

I have tested and I don't think it is your wonderful software that is the issue. I exported a file for a new search from Scopus today and the issue I reported didn't happen (e.g. https://usq-working-folder.s3.us-east-1.amazonaws.com/temp/scopus_test.bib ). There is something in the records that are returned for my particular Scopus search that seem to be causing the issue (i.e. in the bib file at https://usq-working-folder.s3.us-east-1.amazonaws.com/temp/scopus_447.bib ).

Any assistance is appreciated :)

**Comment by Valdecy** [comment]
Hello There! I encourage you to try pyBibX version 3.2.2, as the previously reported issue has now been resolved. However, if you encounter further problems or if something else does not seem to be working properly, please do not hesitate to contact me.

**Comment by ecksteing** [comment]
Works perfectly. Thank you so much :)
