### ISSUE TITLE
big file cant resolve

### ISSUE THREAD

**Issue by yqfun** [Valdecy/pyBibX#4]
When I use a large file about 15mb or so, it takes a long time to parse it, and through troubleshooting, I found that there seems to be a triple nested loop problem, but it still takes a long time to be unresponsive, have you encountered this problem?Have you ever encountered this problem?

**Comment by Valdecy** [comment]
If you can send over the .bib file or even just a relevant portion that replicates the issue, I'd be happy to take a closer look to offer more specific guidance.

**Comment by yqfun** [comment]
[all.zip](https://github.com/Valdecy/pyBibX/files/12515154/all.zip)
![image](https://github.com/Valdecy/pyBibX/assets/16739538/18e3d604-fbc4-4e5f-a18d-38f6f9c5710c)

sorry,i forgot it size,almost 45mb....and i find it need lots of time in _read_bib function in pbx.py,
![无标题](https://github.com/Valdecy/pyBibX/assets/16739538/4ef38575-fdbc-402b-8ea7-b010d49bc9c5)
this loop use long time ,is there any way to optimize?

**Comment by Valdecy** [comment]
I appreciate your attention to the computational complexity issue in the previous code version. I've refactored it, reducing the time complexity to an approximate O(n). I've conducted tests using the file you provided, and the program now executes in around 4 minutes. I'd like you to try the updated version, pybibx 3.2.4, to observe these performance improvements.
