### ISSUE TITLE
save archive that i merge

### ISSUE THREAD

**Issue by jpalma-duque** [Valdecy/pyBibX#6]
Is there any way to save the file I generate by merging many databases to continue working later?

**Comment by Valdecy** [comment]
Please try pyBibX version 3.2.8.  

1) Input a .bib to instantiate a class => bibfile  = pbx_probe(file_bib = file_name, db = database, del_duplicated = True)
2) Then made the modifications and save the data externally => bibfile.save_database(sep = '\t', name = 'data.csv')
3) To load the modified .bib file ( 'data.csv') => bibfile.load_database(name = 'data.csv')
PS: Even with the saved 'data.csv', you always need to do step 1, so to be fast, have any small .bib file in hand. Then, you can go directly to step 3, and your saved .bib ('data.csv') will replace the small .bib

Thank you so much for the suggestion!
