### ISSUE TITLE
Issue with uploading scopus file to produce report

### ISSUE THREAD

**Issue by thepinkclimate** [Valdecy/pyBibX#8]
Hi, when running the pbx_probe command, I get the following error message:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __get_citations(self, series)
   1241                     try:
-> 1242                         citation[i] = int(citation[i])
   1243                     except:

ValueError: invalid literal for int() with base 10: 'all open access, hybrid gold open access'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
3 frames
[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __get_citations(self, series)
   1242                         citation[i] = int(citation[i])
   1243                     except:
-> 1244                         citation[i] = int(re.search(r'\d+', citation[i]).group())
   1245             else:
   1246                 citation[i] = 0

AttributeError: 'NoneType' object has no attribute 'group'

My file is entirely downloaded from scopus. Thank you

**Comment by Valdecy** [comment]
Can you send me the .bib file?

**Comment by thepinkclimate** [comment]
Sure, here you are.

Best
 output_file.bib
<https://drive.google.com/file/d/1qtZjWNBCzQlJrHTKr3j0hZUATubMdguh/view?usp=drive_web>
regards,
Francesca

**Comment by thepinkclimate** [comment]
Dear Valdecy,

I tried with another bib files and unfortunately I got the same issue.

Thank you for your cooperation with this.

Best regards,
Francesca

**Comment by Valdecy** [comment]
Dear Francesca,

I'm pleased to inform you that the issue you encountered has been resolved in PyBibX version 3.3.0. However, it appears that the size of your .bib file significantly extends the processing time. I recommend refining your search query to enhance your experience and achieve faster results. This adjustment should allow for more efficient management and quicker access to your desired outcomes.

Best regards,
Valdecy
