### ISSUE TITLE
Erro ao subir .txt Pubmed

### ISSUE THREAD

**Issue by ionnss** [Valdecy/pyBibX#9]
**Quando vou carregar o arquivo .txt utilizando os argumentos descritos:**
`file_bib = 'pubmed.txt'
database  = 'pubmed'
bibfile   = pbx_probe(file_bib = file_bib, db = database, del_duplicated = True)`

**Ocorre o seguinte erro:** 
`[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __init__(self, file_bib, db, del_duplicated)
    388                                     '#f4d054', '#fbdd7e', '#ffff7e', '#cd7584', '#f9bc08', '#c7c10c'
    389                                   ]
--> 390         self.data, self.entries = self.__read_bib(file_bib, db, del_duplicated)
    391         self.__make_bib()
    392 

[/usr/local/lib/python3.10/dist-packages/pyBibX/base/pbx.py](https://localhost:8080/#) in __read_bib(self, bib, db, del_duplicated)
    931             for i in range(0, len(f_list)):
    932                 if (len(f_list[i]) > 0):
--> 933                     if (len(f_list) > i and len(f_list[i]) >= 5 and f_list[i][4] == '-'):
    934                         f_list[i] = f_list[i][:4] + '=' + f_list[i][5:]
    935                     if (f_list[i][:3] == 'LID'):

IndexError: string index out of range`

![Captura de Tela 2024-04-10 às 12 27 55](https://github.com/Valdecy/pyBibX/assets/39104500/0fcca4ac-6d75-4db7-9f2d-fb62dc163384)

**Comment by Valdecy** [comment]
Olá! Vc poderia me mandar seu arquivo .txt? Vou tentar reproduzir esse erro.

**Comment by Valdecy** [comment]
Eu testei a biblioteca com um arquivo pubmed (.txt) recente e parece tudo normal. O arquivo foi baixado conforme as instruções do README.md -> PubMed: Search, select articles, click "Save," choose "PubMed" format, click "Save" to download a .txt file.
